### ISSUE TITLE
Sunlight won't propagate through the labirynth - the mod directly sets blocks in ExtendedBlockStorage

### ISSUE THREAD

**Issue by Niko-sk2x** [Foghrye4/Labyrinth#2]
The mod should NEVER set blocks directly in ExtededBlockStorage and should never have the need to set the light array. Instead you should offset the blocks you set by 8 in each direction and set them through World. Yes, it won't be as fast. Mainly because you are skipping a lot of the things that make it slow that will cause issues.

![2017-05-18_06 16 24](https://cloud.githubusercontent.com/assets/1349112/26186450/4283dfbc-3b92-11e7-9ec4-2803c0fbdcbf.png)

Or you might have better luck creating new Labirynth world type (a cubic chunks one) with your own chunk generator, that doesn't even bother doing anything below the point where your structure starts, and place just them and nothing else. This would have the obvious downside that it won't support any world types that you don't intend it to support.

Or it can be done as early structure generator, I can add an event to add custom ones. You would work with CubePrimer there. And then only add tile entities in populator.

**Comment by Foghrye4** [comment]
>Sunlight won't propagate through the labirynth

Not my fault. Bug exist in standalone Cubic chunks as well. To repeat: create new world and fill 200-300 blocks with air, while standing on top block. Some of a layers will remain dark. Whenever you remove by hand nearby block in dark zone, light propagate itself further.
http://imgur.com/QP0HIZs

To be accurate, labyrinth generated upper from natural generated terrain layer is lit fully by sunlight (layer above does not cast any shadow).

**Comment by Niko-sk2x** [comment]
This is completely different bug. In this case I described, the lighting code thinks that space if filled and the **heightmap** value won't go lower until you **place and break again every single block there**

**Comment by Niko-sk2x** [comment]
Also I'm almost completely sure that the light not spreading down in the  standalone cubic chunks is client-only. Quit the world and join again a while after you did the command and it should spread just fine.

**Comment by Foghrye4** [comment]
Fixed.
