### ISSUE TITLE
Latest CubicChunks changes broke Labirynth

### ISSUE THREAD

**Issue by Niko-sk2x** [Foghrye4/Labyrinth#3]
You were using the Column class which got removed. Now there is IColumn.

**Comment by Foghrye4** [comment]
I don't remember where I'm using Column. Anyway, it's working fine with latest Cubic chunks version.

**Comment by Niko-sk2x** [comment]
I downloaded the version from minecraftforum and it crashed before so it was definitely using it somewhere.

**Comment by Foghrye4** [comment]
Please fix a CubicChunks build or tell me how to use project as depency. I tried to use a line
```compile project(':CubicChunks')```
But it tells me:
```FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':compileJava'.
> Configuration with name 'default' not found.
```

**Comment by Niko-sk2x** [comment]
you need to run `setupDecompWorkspace` on CubicChunks before you can do anything with it because of a bug in ForgeGradle (most people don't even seem to consider ti a bug, but whatever)

**Comment by Foghrye4** [comment]
Nope, not helping. "CubicChunks" is a link to a cloned project. `setting.gradle` contain line:
`include 'CubicChunks'`

**Comment by Niko-sk2x** [comment]
You need to cd to the CubicChunks submodule and run `./gradlew setupDecompWorkspace` there. If that won't help, join gitter and we can discuss it.

**Comment by Foghrye4** [comment]
Mod tested and its working fine.
