### ISSUE TITLE
world specific settings

### ISSUE THREAD

**Issue by Technoturnovers** [Foghrye4/Labyrinth#5]
The mod should be able to have world specific location settings rather than a global setting so it doesn't fudge up existing worlds. Preferably by world generation menu, but any method is fine

**Comment by Niko-sk2x** [comment]
Using some event to force it into world generation settings string may work, but the right way would probably involve capabilities/WorldSavedData.

**Comment by Foghrye4** [comment]
> it doesn't fudge up existing worlds.

It is already that way. See:
https://github.com/Foghrye4/Labyrinth/blob/master/src/main/java/labyrinth/world/WorldSavedDataLabyrinthConfig.java
