### ISSUE TITLE
Crash with latest current jenkin build for Cubic chunks and forge 1.12.2 

### ISSUE THREAD

**Issue by Darkmega18** [Foghrye4/Labyrinth#6]
[crash-2018-09-19_16.57.38-client.txt](https://github.com/Foghrye4/Labyrinth/files/2395756/crash-2018-09-19_16.57.38-client.txt)

Exact versions are all in the log.

understandably probably cause it's 1.12.2 and I remember the page saying it's for 1.12.1 but anyways

**Comment by Foghrye4** [comment]
Thank you, fixed.
Here is your new version: http://www.mediafire.com/file/sddlm039bbjsm8c/labyrinth-0.3.0.jar

**Comment by Darkmega18** [comment]
Thanks plenty. :) perhaps you should also post it to the cubic chunks discord incase others want it or try to use it? (and also your forum page)
